### ISSUE TITLE
New chirp URLs

### ISSUE THREAD

**Issue by michael79bxl** [joextodd/chirp.io#2]
http://labs.chirp.io/chirp
http://labs.chirp.io/file

Thanks :D

**Comment by joextodd** [comment]
Thanks for the update @michael79bxl 

I have updated the script accordingly. The only way I could manage to GET the chirp data was by using the /get resource, I noticed there is a deprecated comment in your source code so if there is a better way to get this, please let me know.

**Comment by michael79bxl** [comment]
Hi!

I got the information from the composer page from chirp.io folks
http://labs.chirp.io/composer

Regards

Michael

**Comment by joextodd** [comment]
Great thanks, I assumed you worked for chirp! 

Using the same paths as the composer now, so closing issue.

**Comment by michael79bxl** [comment]
Great thanks. By the way, thanks to your code, I finally get the reed solomon parameters, hurray!

**Comment by joextodd** [comment]
That's good to hear. If you have a reed solomon implementation working that outputs the same error correction characters as the chirp longcode, I would love to see it!

**Comment by michael79bxl** [comment]
Too bad :( i thought you figured it out. Anyway I'm digging into reversed code from Android ARM lib and keep you informed :)

**Comment by michael79bxl** [comment]
Do you have a twitter account?

**Comment by joextodd** [comment]
It is also joextodd, but I don't use it ever.

**Comment by michael79bxl** [comment]
OK. piupiu has its own https://twitter.com/piupiu_ml with news and updates
